### ISSUE TITLE
Bilder verlinken

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#10]
geht leider nicht - da macht das System folgendes: 
![image](https://cloud.githubusercontent.com/assets/23695891/20592105/2ae2b300-b22c-11e6-927a-393f5bbdee2d.png)
(schreibt den LInk als Textlink neben das Bild)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

da geht leider nicht der link button mit dem plus, sonder der normale - du kannst den link button mit dem plus verwenden um die sprechende Url zu bekommen und sie dann beim anderen rein kopieren. Ich hab das mal für Elfi Schlager gemacht

Der Button hier geht für Bilder:  <img width="25" alt="screen shot 2016-11-24 at 12 50 00" src="https://cloud.githubusercontent.com/assets/1157580/20597606/f0c339a6-b244-11e6-87d3-c0582f3b05bc.png">
