### ISSUE TITLE
Russian Menus

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#100]
Lieber Andreas, kannst Du bitte die Russischen Menüs anlegen.
1) im Hauptmenü oben muss der Titel weg
2) die Seitenmenüs bitte anlegen:
ich weiß nicht, wie das mit den URLs ist für Russisch, die Kurse erscheinen z.B. mit der Systemurl (/node/...), bei den anderen Bereichen ist die erste Ebene immer Deutsch. Der Browser kann eh nur Lateinische Schriftzeichen lesen, oder? Was fügen wir da ein?

Hier sind jedenfalls die Übersetzungen:
Kurse: Описание Курсов
Über uns: о нас
Seminarort: место проведения

Danke!!
LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

Was heißt Ausbildung auf Russisch?

**Comment by ursulafeu** [comment]
образование

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, also es müsste jetzt soweit alles Ready für RU sein. Wenn du im Backend unter Course Types die Preise in RUB angibst, sollten sie wie im polnischen auch genommen werden.

Richtig beneiden tue ich dich nicht, leider springt das deutsche Interface immer raus, wenn man eine russische Übersetzung bearbeitet…

Jeder Seite mit einem deutschen Pfad müss nochmal geöffnet und gespeichert werden, dann wird der richtige URL Pfad erzeugt und das entsprechende Seitenmenü erscheint links.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke, klappt wunderbar! 
Ja, ich weiß mittlerweile auswendig, wo die russischen Buttons im Backend zu finden sind. Jetzt hab ich mich eh lang genug drum herum gedrückt die russische Version anzugehen ... ;) LG; Ursula
