### ISSUE TITLE
Layoutfehler RU-Menü links

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#101]
http://ru.viszerale-therapie.at/opisanie-kursov/ekzamen-brusnaa-polost 
Bei den jeweils ersten Unterpunkten im Menü links funktioniert der Aktivstatus nicht. 

danke!

**Comment by Andreas-Schoenefeldt** [comment]
What a strange bug, it seems only to effect this one specific translation... but in all menus.

**Comment by Andreas-Schoenefeldt** [comment]
Realy super strange one - it seems to be some kind of error in the drupal system, that I could not fix localy - I have now added a small javascript logic, to cover it up.

**Comment by ursulafeu** [comment]
👍
