### ISSUE TITLE
Dynamic Price Display From Course

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#105]
Lieber Andreas, 

Florinda hat mich grade informiert, dass für die neuen Kurse 2018 falsche Preise angezeigt werden. 

z.B. hier: http://viszerale-therapie.at/register/1?course-id=307
Die Kurse im Jahr 2018 kosten €590, nicht mehr €570.

Kannst Du das bitte ganz dringend prüfen und korrigieren?! 
Florinda hat schon fast 90 Anmeldungen seit die neuen Kurse online sind.

Und noch eine Bitte beim Formular: 
Default-Einstellung beim Beruf soll Physiotherapeut sein und nicht Arzt, so wie momentan der Fall.

Danke!
LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

ich denke es passt jetzt, aber kannst du bitte noch einmal kurz drüber schauen, ob ich alles bedacht habe?

1000 Dank   
Andreas

**Comment by ursulafeu** [comment]
perfekt!
