### ISSUE TITLE
Capitalize input

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#108]
> Beim Anmeldeformular: Bitte fixe Voreinstellung beim Land – Österreich. Und dass alle Felder mit Großbuchstaben beginnend ausgefüllt werden müssen. Ich muss das sehr häufig händisch korrigieren. Manche füllen es auch alles in Großbuchstaben aus – das ist auch sehr unpraktisch.

- done as a js-widget, which will bring the input into the correct capitalized form.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 
eventuell kannst du das auch einmal kurz anschauen, für den fall das ich etwas offensichtliches vergessen habe?

1000 Dank!

**Comment by ursulafeu** [comment]
Ich konnte nichts fehlerhaftes daran finden. Passt! :)
