### ISSUE TITLE
backend ticket: Anmeldebestätigung als PDF

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#109]
Lieber Andreas,
Florinda hat mir gesagt, dass die Anmeldebestätigung als PDF noch offen ist. 
Wie gehts damit?
LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Ist ein Backend Thema ;) - ich hab ungefähr 50% fertig mach aber erstmal die anderen kleineren anfragen, bevor ihr Sekretärin eingearbeitet wird.

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Please follow up here for this one: https://github.com/Andreas-Schoenefeldt/simple-courses/issues/97
