### ISSUE TITLE
backend ticket: usability issues

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#110]
Lieber Andreas,
ebenfalls eine Bitte von Florinda:

1) Rechnungen alphabetisch, statt nach Rechnungsnummer reihen 
(Du müsstest wissen, worum es geht?)

2) Backend default-mäßig deutsch machen
Ist beim Versand von Dokumenten (z.B. Rechnung oder erneute Zusendung der Anmeldebestätigung) standardmäßig EN. Das sollte bitte DE sein, um Fehlern in der Kundenkommunikation vorzubeugen.

Danke!

**Comment by Andreas-Schoenefeldt** [comment]
Moment, ich lad dich mal ins Backend ein, das ist ein eigenes Projekt, weil ein eigens System.

**Comment by Andreas-Schoenefeldt** [comment]
Please follow up here for this one: 

1.: https://github.com/Andreas-Schoenefeldt/simple-courses/issues/106 
2.: https://github.com/Andreas-Schoenefeldt/simple-courses/issues/108
