### ISSUE TITLE
Text zu Tabs auf Startseite

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#12]

**Comment by ursulafeu** [comment]
Tippfehler beim 1. Tab:
![image](https://cloud.githubusercontent.com/assets/23695891/20599052/6e315b1e-b24c-11e6-9222-60ba42cc5cf1.png)
Tab **Aufbaukurse**: kein Text vorhanden
Text für Tab **Prüfungen:**
Jeder Kursteilnehmer erhält nach erfolgreichem Abschluss eines Kurses eine Teilnahmebestätigung. Darüber hinaus besteht die Möglichkeit eine Masterprüfung in Viszeraler Therapie zu absolvieren.
Hierfür müssen drei Prüfungen bestanden werden. In beliebiger Reihenfolge werden Abdomen- und Thoraxprüfung absolviert und dann die Masterprüfung.

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ich hab den Text angepasst und er ist wird auf der Startseite sein, wenn ich das nächste Deployment mache. Im moment lass ich es mal hardcoded, aber mittelfristig macht es bestimmt Sinn dass so anzupassen, das man es einfach am block konfigurieren kann.
