### ISSUE TITLE
Kursanmeldung - Textkorrekturen

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#14]
**1) ein "Sie" fehlt hier:** 
Den Link zur Versicherung erhalten **Sie** nach Absenden dieses Formulares, sowie in Ihrem Bestätigungsemail.

**2) bitte überall das € vorstellen (ist hier gemischt) - unten der korrigierte Text:**

Umbuchungs- und Rücktrittskonditionen

Den Link zur Versicherung erhalten **Sie** nach Absenden dieses Formulares, sowie in Ihrem Bestätigungsemail.

Umbuchungen:

Im Fall einer Umbuchung (z.B. Kursdatum / Ort / Kurs) ist eine Bearbeitungsgebühr von € 30 zu bezahlen.

Stornogebühr bis 6 Wochen vor Kursbeginn:
Rücküberweisung des einbezahlten Kursbetrages abzüglich € 30 Bearbeitungsgebühr

Stornogebühr 6 - 4 Wochen vor Kursbeginn:
30 % der Kursgebühr + € 30 Bearbeitungsgebühr

Stornogebühr 4 - 2 Wochen vor Kursbeginn:
50 % der Kursgebühr + € 30 Bearbeitungsgebühr

Stornogebühr 2 Wochen vor Kursbeginn oder während des Kurses:
100 % der Kursgebühren + € 30 Bearbeitungsgebühr

**3) dass statt das** und zweiter Satz umgeschrieben (unterschiedliche Ansprache war nicht stimmig)
Ich habe zur Kenntnis genommen, **dass** im Falle einer Schwangerschaft an diesem Kurs nicht teilgenommen werden kann. Im Falle einer Stornierung durch Schwangerschaft gelten unsere Rücktrittskonditionen (siehe oben). *

**4) Adresse Arbeitgeber**
Adresse statt Addresse

**Comment by Andreas-Schoenefeldt** [comment]
Den Teil hier finde ich übrigens Übertrieben: 

> Stornogebühr 2 Wochen vor Kursbeginn oder während des Kurses:
> 100 % der Kursgebühren + € 30 Bearbeitungsgebühr

Wenn man während des Kurses weg geht und sein Geld schon nicht zurück bekommt, soll man auch noch 30 € extra zahlen?

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

ist erledigt - die Klausel "wärend des Kurses" kann vielleicht raus?

**Comment by ursulafeu** [comment]
Ja, irgendwie schon lustig ... aber lass es mal drin, Florinda hat das mit Monika genau ausgearbeitet und da gibt es wohl eine Leidensgeschichte ... sie hat mir erzählt, dass jede Woche einige Umbuchungen vorzunehmen sind und das immer mit Aufwand verbunden ist.

**Comment by ursulafeu** [comment]
wie cool ist das denn - da kann man sogar die Code-Änderungen nachvollziehen!!

**Comment by Andreas-Schoenefeldt** [comment]
Ja, echt cool, oder? Ich mach das Ticket dann als erledigt zu :)
