### ISSUE TITLE
Title zweizeilig darstellen auf Content-Seiten

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#15]
Wir brauchen Umbrüche für Kurstitel - z.B. so:
Zeile 1: Läsionskette
Zeile 2: Urogenitaltrakt – Hüfte/Wirbelsäule
![image](https://cloud.githubusercontent.com/assets/23695891/20641561/dcf03264-b3fa-11e6-845a-112821d5bcbf.png)

**Comment by Andreas-Schoenefeldt** [comment]
Wo es geht, haben wir es jetzt :)
