### ISSUE TITLE
Kursanmeldung - Sektion Arbeitgeber

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#16]
1) Reihenfolge ändern --> erst Arbeitgeber und Adresse, dann Ansprechpartner
2) blaue Headline "Adresse Ansprechpartner" kann weg
3) Statt "Arbeitgeber" bitte: Arbeitgeber / Krankenhaus
![image](https://cloud.githubusercontent.com/assets/23695891/20641594/8ac91c2a-b3fb-11e6-8b19-850737de1963.png)

**Comment by Andreas-Schoenefeldt** [comment]
Fixed 😸
