### ISSUE TITLE
Kursanmeldung - Korrektur

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#17]
1) Länder im Dropdown bitte in deutscher Sprache 
2) Bei Beruf bitte: 
- PhysiotherapeutIn
- RU & UA: andere med. Ausbildung ODER
Russl.&Ukraine: andere med. Ausbildung

![image](https://cloud.githubusercontent.com/assets/23695891/20641624/15d147ca-b3fc-11e6-827c-962e09259d71.png)

**Comment by Andreas-Schoenefeldt** [comment]
Done
