### ISSUE TITLE
Kursanmeldung - Voraussetzungen

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#19]
**1) Funktionalität**
Für eine Teilnahme beim Masterkurs müssen beide Aufbaukurse absolviert worden sein (Thorax und Abdomen) - dann stimmt leider unser Text nicht mehr ...
d.h. wir brauchen 2 Möglichkeiten:
a) Kursvoraussetzung ist Kurs A ODER Kurs B
b) Kursvoraussetzung ist Kurs A UND Kurs B

--> entweder es steht oben ein anderer Text, oder wir kriegen zwischen den Zeilen ein ODER und ein UND rein ... ?! Was ist machbar?

**2) Textänderung für den optional absolvierten Kurs:**
für die Option mit Anzeige eines ODER möchte Florinda ganz kurz und knapp schreiben:

_Kursvoraussetzung:_

wenn das nicht geht und wir statt dessen oben einen anderen Text anzeigen, dann bitte für die ODER-Variante folgenden Text:
Voraussetzung für die Teilnahme - einer der folgenden Kurse wurde bereits besucht:

für die UND-Variante:
Voraussetzung für die Teilnahme - alle nachfolgenden Kurse wurden bereits besucht:

**Comment by Andreas-Schoenefeldt** [comment]
Spannend 😏 Also aus optischer Sicht bin ich stark für eine Textänderung. Wir können das **und** oder **oder** ja fett machen? Ich muss da noch das Backend für anpassen, im Moment kann es nur ein implizietes und.

**Comment by ursulafeu** [comment]
habe im Backend alles entsprechend eingegeben.

**Comment by ursulafeu** [comment]
bitte noch das Ausrufezeichen austauschen und die Textänderung mit UND / ODER (find ich gut in fett geschrieben). Dann steht oben nur _Kursvoraussetzung:_

**Comment by Andreas-Schoenefeldt** [comment]
Wird jetzt im Frontend auch ausgewertet 😸

**Comment by ursulafeu** [comment]
ich sehe leider noch die alte version (trotz Browser und Drupal Cache leeren) ?
![image](https://cloud.githubusercontent.com/assets/23695891/20701461/647f579a-b613-11e6-8be0-2da25816d526.png)
