### ISSUE TITLE
Footer - Übersetzungen

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#20]
Ich hab für den Footer eine Übersetzung EN angelegt. Jetzt ist auch auf der DE-Version immer die englische Übersetzung zu sehen. Wie geht das bitte?

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 

also bei Blöcken gibt es zwei Layer - einmal den Block ( **block Übersetzen** der hat die Attribute, wie Titel und wo er angezeigt wird - das sollte eigentlich nicht nötig sein zu übersetzen. Wenn doch, muss man die Übersetzung glaube ich für die entsprechende Sprache einschränken)

<img width="446" alt="screen shot 2016-11-28 at 14 11 24" src="https://cloud.githubusercontent.com/assets/1157580/20669594/57666e84-b575-11e6-80dc-da1f696036e6.png">

Der echte Punkt ist **Übersetzen**, dort kann man nur eine Sprachversion des im Blocks angezeigten Inhalts erstellen. Das ist definitiv die bevorzugte Option und sollte als erstes versucht werden. Im Fall von Footer gibt es dort noch keine Englische Übersetzung:

<img width="968" alt="screen shot 2016-11-28 at 14 19 28" src="https://cloud.githubusercontent.com/assets/1157580/20669684/c39e2088-b575-11e6-8547-61ccdd582595.png">
