### ISSUE TITLE
Übersetzung Menu

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#21]
Sobald ich einen Menüpunkt übersetze ist auch die De-Version mit Englisch überschrieben ... ):
Ich mache das hier (siehe Screenshot), da man das Menu an sich nicht übersetzen kann (unter STruktur - Hauptnavigation).
![image](https://cloud.githubusercontent.com/assets/23695891/20647434/705e920e-b494-11e6-91e5-7a33a6b6478f.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

ich bin nicht sicher, aber das scheint eine Art bug im System zu sein. Ihc habe eben eine neue Test Seite erstellt, und dort geht es. Kannst du die Seite bitte einmal neu erstellen und schauen ob es dann immer noch so ist?

Ich hoffe das müssen wir jetzt nicht mit allen Seiten machen...

Ansosnten könnten wir auch für jede Sprache eine Version des Hauptmenüs anlegen und die Seite nur dort einbinden. Dann kann man auch die Struktur der Seite für jede Sprache Individuell anpassen.
