### ISSUE TITLE
Kursübersucht Content

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#24]
Hi Ursula :),

Ich hab jetzt auf http://preview.czeija.com/kursuebersicht die Draft Version der Kursübericht eingebaut. Die fancy icons fehlen noch, aber funktional ist es glaube ich gut. Stellst du noch den Content oben auf der Seite ein oder gibt es schon eine andere Kursübersichtsseite?

1000 Dank
Andreas

**Comment by ursulafeu** [comment]
der Content ist drin, ich kann das Bild allerdings nicht formatieren, sodass der Text rundherum fließt. http://preview.czeija.com/kursuebersicht

PS: kannst du bitte im Editor wieder rechts / linksbündig einblenden? das geht zwar eh nicht für Bilder, aber für Text brauch ich es.

**Comment by Andreas-Schoenefeldt** [comment]
Ich hab es jetzt so gemacht, das nur noch das Full Html Format drin ist - ich glaube du hattest nur das einfache html drin gehabt.

**Comment by Andreas-Schoenefeldt** [comment]
Ich stell dir noch ein left und right ein für die Bilder als Stil, das geht ja so nicht....
