### ISSUE TITLE
Styling for Blocks

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#26]
Hi Ursula,

die Blocks können jetzt auch mit dem Rahmen versehen werden

**Bearbeiten**   
<img width="388" alt="screen shot 2016-11-28 at 18 46 32" src="https://cloud.githubusercontent.com/assets/1157580/20679512/82299b5c-b59b-11e6-9945-27bc2baed734.png">

Das entsprechende Format einstellen. Ich habe auch die mit hinzugefügt, die wir an anderen Stellen schon haben. Die blaue und die graue Box.   
<img width="404" alt="screen shot 2016-11-28 at 18 46 43" src="https://cloud.githubusercontent.com/assets/1157580/20679535/a1138460-b59b-11e6-8b9b-ca4f5f5c1fcf.png">

Liebe Grüße    
Andreas

**Comment by ursulafeu** [comment]
das wird bei mir leider nicht angezeigt - auch mit geleertem Cache. Ich verwende Chrome und Safari.

**Comment by Andreas-Schoenefeldt** [comment]
Ah, da hat noch eine Einstellung gefehlt. Jetzt ist es da.

**Comment by ursulafeu** [comment]
passt!
