### ISSUE TITLE
Template - Korrektur Hand und linke Leiste

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#28]
Hand links oben und linke Leiste
![image](https://cloud.githubusercontent.com/assets/23695891/20684018/8bbe15b8-b5ae-11e6-9fd5-8a252b9eef21.png)

**Comment by Andreas-Schoenefeldt** [comment]
Das war ja ziemlich interessant die linien und balken da so hin zu bekommen 😂 - würdest du die Menüstruktur unter http://preview.czeija.com/admin/structure/menu/manage/kurse jetzt so wie gewünscht aufbauen?

Brauchen wir noch irgendwo auf der Seite ein Seitenmenü? Unter Team vielleicht?

1000 Dank
Andreas

**Comment by ursulafeu** [comment]
Ja bitte bei allen Menüpunkten AUSZER Therapeutenliste und Kontakt.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

das verwendete Seitenmenü kannst du jetzt easy über das feld "Seitenmenü" einer Seite entsprechend einbinden. Automatisch wird das Menü leider nicht gerendert, die Sieten müssen dort also noch einmal manuell eingebunden werden.

<img width="299" alt="screen shot 2016-11-30 at 00 11 07" src="https://cloud.githubusercontent.com/assets/1157580/20734480/b334d1f2-b691-11e6-9287-8ead29db20ec.png">

**Comment by ursulafeu** [comment]
Klappt super, danke. 
**Das Menü hast Du auch super schön gestylt - danke!
Einen Abstand bräuchten wir noch größer bitte** - der erste Menüpunkt sollte auf gleicher Höhe anfangen wie die Headline im Content, siehe Screenshot:
![image](https://cloud.githubusercontent.com/assets/23695891/20745876/80b87416-b6e3-11e6-8f95-7d1f8c3638f4.png)

**Comment by ursulafeu** [comment]
ich hab den letzen punkt hier in die Styling-Korrekturliste gefügt, ist für den moment ja nicht essentiell.
