### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#29]
1) Funktionalität Hauptnavigation

2) Aktivstatus Hauptnavigation fehlt noch - siehe Layout:
![image](https://cloud.githubusercontent.com/assets/23695891/20684160/15f17d92-b5af-11e6-82b9-518aa6d40bce.png)

3) Erstellen der Alternativ-Navigation im linken Bereich

**Comment by Andreas-Schoenefeldt** [comment]
Soweit so gut ;) - was denkst du zur mobilen Version?
