### ISSUE TITLE
Template - Sprachen und Kursübersicht

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#30]
1) Layoutanpassung Sprachen und Verlinkung Sprachversionen auf alte Seite
2) Kursübersicht einfügen laut Layout
![image](https://cloud.githubusercontent.com/assets/23695891/20684553/c20f26d2-b5b0-11e6-99be-47bac3b33a40.png)

**Comment by Andreas-Schoenefeldt** [comment]
Done :)
