### ISSUE TITLE
Layout Korrekturen - Kleinigkeiten

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#31]
Kursdetailseite** 
bitte Abstände rechts zwischen den einzelnen Blöcken verringern - halb so viel Abstand reicht. Danke!
![image](https://cloud.githubusercontent.com/assets/23695891/20830529/2955aed8-b881-11e6-8fac-0f0fc6f887b3.png)

**4) Kursübersicht und Sprachen rechts oben**
das soll eigentlich nach ganz außen rechts, also mit der rechten Spalte abschließen. danke
![image](https://cloud.githubusercontent.com/assets/23695891/20830571/5758b74e-b881-11e6-9fb0-32acda5d0b9f.png)

**Comment by Andreas-Schoenefeldt** [comment]
HI Ursula, this two adjustments are now fixed :)

**Comment by ursulafeu** [comment]
danke!
