### ISSUE TITLE
Kursanmeldung - testen nicht möglich

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#32]
![image](https://cloud.githubusercontent.com/assets/23695891/20684851/21665f1e-b5b2-11e6-887a-8c5326a7f83d.png)

**Comment by ursulafeu** [comment]
wollte die Danke-Seite testen.

**Comment by Andreas-Schoenefeldt** [comment]
Ups, das ist ja spannend - ich schaue rein. Danke fürs Testen!

**Comment by Andreas-Schoenefeldt** [comment]
Ok, da hatte sich noch ein Fehler iengeschlichen. Ist jetzt behoben
