### ISSUE TITLE
Funktionalität - Schnellanmeldungs-Formulare

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#35]
Bitte für die Deutsche Sprachversion Salzburg als Vorauswahl einstellen.
Für die anderen Sprachversionen gilt dann das gleiche mit dem jeweiligen Standort.
Englische Sprachversion kann so bleiben wie jetzt der Fall.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, is this still an issue, or are we happy with the form, as it is?

**Comment by ursulafeu** [comment]
passt so, danke.
