### ISSUE TITLE
Home Kursboxen

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#37]

**Comment by ursulafeu** [comment]
1) "Infos" richtig verlinken
2) "Kurs Buchen" --> bitte ändern auf: "Kurs buchen"

**Comment by Andreas-Schoenefeldt** [comment]
Das mit dem Link war ja noch richtig spannend :D - er wird jetzt auf grundlage der course type id vom backend an der Seite gesetzt. Passt perfekt :D 

Wenn alles soweit ok ist, kannst du das Ticket zu machen.

Liebe Grüße    
Andreas

**Comment by ursulafeu** [comment]
alles super, danke!
