### ISSUE TITLE
mobile version

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#38]
Ich hab mal die mobile Version gecheckt. Bitte schau nochmals die Variante laut Design an. 
1) Logo soll größer sein
2) ÖCERT unten, statt oben
3) Darstellung der Kurs-Tabs war anders geplant – hier ist das Bootstrap Template, in dem die Tabs verwendet werden: http://blackrockdigital.github.io/startbootstrap-modern-business/services.html
4) Schnellanmeldung bitte ausblenden
5) es gibt ein Problem mit der Darstellung von normalen Content Bildern - siehe Bild
![img_3916](https://cloud.githubusercontent.com/assets/23695891/20745601/64354b76-b6e2-11e6-9bfa-1061d93100b4.PNG)

![01 home mobile](https://cloud.githubusercontent.com/assets/23695891/20745487/e3d305a4-b6e1-11e6-96ab-3681cad76193.jpg)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

also mit den content Bildern müssen wir nochmal schauen, wie wir da eine gute Lösung finden. zumindest die height muss immer auf **auto** stehen

Ich denke mal es sieht jetzt ganz gut aus  und sollte alles soweit drin sein, wie gewünscht :)

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
wegen Bilder auf "auto" Höhe musst Du mir bitte mal zeigen. Das Größen-Veränderungstool, das Du eingebaut hast macht das glaube ich automatisch "falsch"?
**Jedenfalls - die mobile Version ist richtig richtig klasse geworden !!! DANKE**
