### ISSUE TITLE
Anpassungen Kursübersichtseite

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#39]
> * Hier fände ich es gut wenn rechts der Button wäre für Anmeldung - ich denke nicht dass jeder automatisch erkennt unter den Physios wenn es grau wird dass es dann schon möglich ist sich anzumelden - musss nicht sofort sein
> * auch hier fände ich es gut meinen einen grünen oder roten Punkt zu signalisieren ob er schon ausgebucht ist - damit sie sich nicht durchklicken müssen - wichtig

Sag mal @ursulafeu wie machen wir das mit dem grünen Punkt? An sich fänd ich das ja richtig cool, aber ich will auch nicht einfach nur nen grünen Punkt rein knallen.

**Comment by ursulafeu** [comment]
so mit Florinda vereinbart - Balken bei Mouseover grau oder blau:

![image](https://cloud.githubusercontent.com/assets/23695891/20981361/b5c1feb2-bcb4-11e6-8f75-b942764940de.png)

**Comment by Andreas-Schoenefeldt** [comment]
That's done, right?

**Comment by ursulafeu** [comment]
perfect!
