### ISSUE TITLE
Anpassungen Kursbeschreibungen

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#40]
> * beim Kursort finde ich es gut wenn zuerst Salzburg/Schloss Mattsee steht und dann erst die anderen Kursorte - besonders bei der deutschen Homepage, da ja so gut wie die meisten Kurse in Salzburg stattfinden.
> * bei Terminwahl würde ich zuerst das Datum, den Namen und dann ausgebucht hinschreiben - ist fürs Auge nicht so angenehm

* Kursort des Landes der aktuellen Sprache sollte zuerst ausgewählt sein
* check dass language im cache tag ist
* umschreiben des Datums

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

this is solved meanwhile, no?

Best wishes
Andreas

**Comment by ursulafeu** [comment]
solved! :)
