### ISSUE TITLE
Anmeldung - Name der Terminauswahl

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#41]
> bei Terminauswahl sind die Namen so halb sichtbar - kann man da nur die Nachnamen nehmen wenn es zuwenig Platz gibt? besser wäre aber bestimmt der ganze Name

Ok, also das können wir nur mit custom select inputs erreichen. Ich schaue rein, aber ich sehe es nicht als kritisch für den Livegang. Ist in meinen Augen eher ein Detail.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursual,

this is now already solved by the new dynamic multiline inputs, right?

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Hi Andreas, to be honest, I don't know what this is about? ;) Can you please explain or send a screenshot, thank you!
