### ISSUE TITLE
Save of entered form data in error case

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#43]
At the moment all entered data is cleared if an error occured. I did not utilize the drupal forms, which might bring this feature already per default. Could you please check, weather it could made possible to still have the values in the form in case of an error?

The most common error is if you try to register twice.

Thx a lot
Andreas

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt 

We couldn't reproduce this issue:
> The most common error is if you try to register twice.

Please provide the steps to reproduce it.

**Comment by Andreas-Schoenefeldt** [comment]
Hi friends,

# register once to a course on the local website
# you see the success message
# register again for the same course , use the same email
# you will see an error message
# the form data is cleared. - can the data taht you have entered in the first place, still be available?

**Comment by cydgit** [comment]
Hi Andreas,

Yes, we could reproduce that.
And regarding 5 - yes. the data can be saved.

Kind Regards,
Dmitry

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , this is to double check this with you.
The only option to save data is to add them to the URL upon the form submit, i.e. the URL will look like this: "de/register/1?q=firstname='Test'&lastname='Test Lastname'"
This is because the form is implemented in HTML, not using the standard Drupal API.
So this would be the quickest solution. Another option (which would take more time) is to re-create the form using Drupal form API.
Please let me know which option we should apply.

**Comment by Andreas-Schoenefeldt** [comment]
let's go with the first option, thx a lot.

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt 
Need some clarifications here.
Currently selects are displayed as HTML elements in template files currently.
For example:

```
<select name="salutation" id="salutation" class="form-control widget" data-widgets="chosen" required>
<option value="1">{% trans %}Frau{% endtrans %}</option>
<option value="2">{% trans %}Herr{% endtrans %}</option>
</select>
```

To save the data and display them in selects we'll have to use one of the following options:
1. Re-write selects like that:

```
$options = array(1 => array('value' => '1', 'text' => 'Frau'), ...);
<select name="salutation" id="salutation" class="form-control widget" data-widgets="chosen" required>
{% for option in options %}
<option value={% option.value %} {% option.selected %}>{% option.text %}</option>
{% endfor %}
</select>
```

2. Process in JS.
3. Ignore selects in scope of this task.

We find the first option the most suitable. Please let us know your thoughts.

Cheers,
Dmitry

**Comment by Andreas-Schoenefeldt** [comment]
Hi Dimitry, 
yes, I also think the best solution is Nr. 1 - the label should still be translatable via the translate interface thou and it might be a bit of a hassle for the country forms.

Please note, that country selects have a default select (RU for Russia, AT for German language, etc)

to have it a bit more slick, i would also suggest such a structure:
```
$options = array ('1' => array('label' => t('Frau'), selected => 'selected'), 'next value' => array('label' => t('Herr')))
<select name="salutation" id="salutation" class="form-control widget" data-widgets="chosen" required>
{% for value, option in options %}
     <option value={% value %} {% option.selected  %}>{% option.label %}</option>
{% endfor %}
</select>
```

Thx a lot
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
beautifull, thx a lot!
