### ISSUE TITLE
Anmeldebestätigung - Titel werden nicht angezeigt

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#44]
> * hier hatte ich mit Dr. und BSC angemeldet aber die Titel sind im Email nicht übernommen worden
> *  hier steht nochmals der Satz: Falls Ihr Arbeitgeber die Kursgebühr überweist, geben Sie bitte die Rechnungsanschrift Ihres Arbeitgebers an. Dieser ist verwirrend - hier sollte dann stehen, wenn sie einen Arbeitgeber angegeben haben. `Ihre Rechnung wird auf folgenden Arbeitgeber ausgestellt.`

**Comment by Andreas-Schoenefeldt** [comment]
This is a backend Ticket.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I made the tiles now available and also extended the templates with ```${customer.title} ${customer.lastname}${customer.intlTitle}``` - both tiles should now be correctly part of the email. 

Could you please check it once?

**Comment by ursulafeu** [comment]
Das passt alles - der Titel wird angezeigt.
Der Satz mit der Rechnungsanschrift kommt so nicht vor. Da steht folgender Satz, der inhaltlich auch passt, zumindest nicht Verwirrung stiftet: 

Arbeitgeber: ...
Zahlung:
Bitte zahlen Sie die Kursgebühr bis 6 Wochen vor Kursbeginn ein. Zeitgerecht wird Ihnen automatisch Ihre Rechnung per Email zugesandt.
Bankverbindung für Kurse in Österreich: Florinda Czeija IBAN AT341420020011544267 BIC EASYATW1Umbuchung und Stornierung:Bei jeder Umbuchung bzw. Stornierung fallen Bearbeitungs- bzw. Stornogebühren an.
