### ISSUE TITLE
Anmeldebestätigung - Umschreibung des Inhalts

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#45]
Hallo Ursula,
> * wenn man auf den Link mit Geschäfts und Stornobedingungen geht geht dieser nicht
beim Link für die Stornoversicherung kommt im Moment der falsche link - was ist der richtige - kenne mich hier nicht mehr aus - sorry
> * es fehlt hier der Satz, dass das Diplom per Email (Foto, Scan) etc. an die Schule geschickt werden muss - das vergessen sie sonst
> * Auf Ihren Wunsch wurden Sie auf die Warteliste gesetzt und werden rechtzeitig auch über einen eventuellen neuen Kurstermin informiert: Nein
>    * das verwirrt die Leute sehr - da bekomme ich immer wieder die Anfrage, ob sie nun auf der Warteliste sind oder fix einen Platz haben - das sollte ja jetzt aber anders sein oder - weil man klickt ja die Warteliste nicht mehr an oder????

könntest du das eventuell machen? Die Emails kann man als full html hier bearbeiten: http://backend.czeija.com/show/Template

* Registration Confirmation Email - Customer
* Registration Confirmation Overbooked Email - Customer

Das wäre sehr toll, vielen Dank! Es ist eine sehr einfache Templatesprache, wenn sich die nicht sofort erschließt, ruf mich gerne an.

**Comment by ursulafeu** [comment]
Drei Sachen waren im Text zu ändern:

**1) Hinweis auf Zusendung des Diploms** - ist erledigt

**2) Rechnungsadresse Arbeitgeber** - hier war ich unsicher, da ein dynamischer Tag dabei steht.
das soll weg:
Falls Ihr Arbeitgeber die Kursgebühr überweist, geben Sie bitte die Rechnungsanschrift Ihres Arbeitgebers an.
${billing}
statt dessen wollte Florinda das:
Ihre Rechnung wird auf folgenden Arbeitgeber ausgestellt:

**3) Warteliste** ist auch noch angeführt - das kann hier ja komplett gelöscht werden, oder?
Bitte kannst Du es noch rauslöschen wenn das passt.
Auf Ihren Wunsch wurden Sie auf die Warteliste gesetzt und werden rechtzeitig auch über einen eventuellen neuen Kurstermin informiert: ${customer.acceptsWaitinglist}

**Comment by ursulafeu** [comment]
_"wenn man auf den Link mit Geschäfts und Stornobedingungen geht geht dieser nicht
beim Link für die Stornoversicherung kommt im Moment der falsche link - was ist der richtige - kenne mich hier nicht mehr aus - sorry"_

Hier meinte Florinda den Absatz im Formular. Ich find die Funktion recht schön, dass man den ganzen Text anklicken kann, um das Häkchen zu setzen. Kann man dahinter noch den Link zu den AGB einfügen, sodass er klickbar ist?

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, ich habe jetzt den link noch direkt im feld mit eingefügt - es geht dann beides :). Fehlt hier noch etwas oder passt es dann so?

**Comment by ursulafeu** [comment]
Bei mir sieht das so aus wie vorher? Sprechen wir vom gleichen?
![image](https://cloud.githubusercontent.com/assets/23695891/20977077/b1f07e22-bca4-11e6-99a6-fe21d3b9f7aa.png)

**Comment by Andreas-Schoenefeldt** [comment]
ich glaub ein Tikcet hierzu reicht ;).
