### ISSUE TITLE
Email-Templates: Link AGB nach Live-Going korrigieren

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#47]
Wir müssen nach Live-Going den fixen Link zu den AGB korrigieren.

jetzt: http://viszerale-therapie.at/pdf/Allgemeine_Geschaefts-und_Stornobedingungen.pdf
dann: http://viszerale-therapie.at/agb

**Comment by Andreas-Schoenefeldt** [comment]
Done für DE :)
