### ISSUE TITLE
Mobile: SVG Logo and Gradient

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#48]
This ticket is about replacing the current png logo by an svg file and to use a css3 gradient for the layout. 

I attach the mobile and standard view as designed by @ursulafeu 

**Mobile Home (with gradient):**
![01 home mobile](https://cloud.githubusercontent.com/assets/1157580/22289053/ee258114-e2f9-11e6-84f9-c13b0f484eba.jpg)

**Desktop Home (without gradient):**
![01 home](https://cloud.githubusercontent.com/assets/1157580/22288996/a5153884-e2f9-11e6-96f4-0f5c60d00f70.jpg)

and the svg icons:
[logos.zip](https://github.com/Andreas-Schoenefeldt/vt.at-drupal/files/729407/logos.zip)

**Comment by ursulafeu** [comment]
hab ich Dir per Email geschickt. Die Größe ist minimal größer als im Template.
Melde Dich bitte wenns noch einer Änderung bedarf.

**Comment by ursulafeu** [comment]
das korrigierte SVG hab ich Dir am Freitag geschickt. :)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Guys, for everything smaller then screen-md we are still missing the gradient behind the logo. Could you add it please, starting from @vt-lighter-blue to white. Please use css 3 gradient for this.

Thx a lot
Andreas

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , implemented for everything smaller than screen-md (992px): mobile, tablet, medium devices/desktop.
Please let us know if anything else is needed here.

**Comment by ursulafeu** [comment]
[logos PL and RU.zip](https://github.com/Andreas-Schoenefeldt/vt.at-drupal/files/811214/logos.PL.and.RU.zip)
can you please change the logos for language versions PL and RU ---> both SVG files are in the zip-file. Thank you!
