### ISSUE TITLE
desktop view in small resolution

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#49]
the problem is (see screenshot). The logo is cut and the two lined navigation is not realy clickable. Could the distance between the menu points could be made smaller for this resolution?
![image](https://cloud.githubusercontent.com/assets/23695891/20857381/b7c22ef4-b92a-11e6-9ece-6c63108b4af6.png)

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt 
What should be the color of the active 'Team' link, if we're on a child menu item? For example, here:
http://viszerale-therapie.at/ueber-uns/elfi-schlager

Currently the text is white if this menu item ('Team') is active.

**Comment by ursulafeu** [comment]
Hello both, I hope this is helpful. This is what it should look like:
![image](https://cloud.githubusercontent.com/assets/23695891/23373657/4263a968-fd21-11e6-8dbb-ced9c038a61a.png)
The background-color for mouse-over on hover-menu is: #DEE2ED

**Comment by ursulafeu** [comment]
by the way - the style for main menu on hover is also not correct yet.
The font should be bold on mouse-over instead of a blue background. (see screenshot above)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this has now a smaller distance for the small desktop resolution
