### ISSUE TITLE
Domain viszerale-therapie.com

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#50]
Lieber Andreas, 
es gibt zwei Domains für deutschsprachig:
1) www.viszerale-therapie.at (Hauptdomain, wird auch in den Drucksorten verwendet)
2) www.viszerale-therapie.com

Die zweite Domain zeigt noch auf die alte Webseite. Ich bin nicht sicher, ob wir uns richtig verstanden haben, oder ob Du es noch nicht gemacht hast ... Das sollten wir dringend ändern bitte.
danke!

**Comment by Andreas-Schoenefeldt** [comment]
Um ganz klar zu sein: pro Sprache sollte es genau eine Domain geben. das heißt die 
www.viszerale-therapie.com wird nur englischen content ausliefern. Ich ändere das in den nächsten Stunden

**Comment by ursulafeu** [comment]
nein, für den EN Content gibts www.visceral-therapy.com

**Comment by Andreas-Schoenefeldt** [comment]
dann leiten wir die www.viszerale-therapie.com direct auf www.viszerale-therapie.at um, eine Seite soll nut unter genau einer domain verfügbar sein.

**Comment by Andreas-Schoenefeldt** [comment]
Done :) 

Mein Whatsapp ist übrigens gerade ausgefallen und ich bin momentan nur über email oder Skype erreichbar. Emails lese ich unregelmäßig, also bei dringenden Sachen am besten Skype (sehr altes Handy... )

**Comment by ursulafeu** [comment]
genau so! danke.
