### ISSUE TITLE
Text Dankeseite - Stornohinweis einfügen

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#52]
**STORNOVERSICHERUNG:**
Um anfallende Kosten für eine Stornierung des Kurses (z.B. wegen Schwangerschaft, Krankheit) zu vermeiden, raten wir dringend zum Abschluss einer Stornoversicherung! 

Versicherungskosten: je nach Kurs, zwischen € 12 und €34 (5% der Kursgebühr)
Anbieter: Europäische Reiseversicherung (ERV)

Die Stornoversicherung kann in wenigen Schritten online abgeschlossen werden.

**Jetzt online abschließen:** http://start.europaeische.at/stesv?AGN=10020922

**Stornierung aufgrund von Schwangerschaft:** 
Ausschließlich für Kursteilnehmerinnen der Schule für Viszerale Therapie ist auch Schwangerschaft als Grund für eine Stornierung versichert. Die Zusatzklausel hierfür lautet:
_"Eintritt einer Schwangerschaft der versicherten Person, wenn die Schwangerschaft erst nach Versicherungsabschluss festgestellt wurde“._

ACHTUNG! Um die vereinbarten Sonderkonditionen zwischen unserem Versicherungspartner ERV und der Schule für Viszerale Therapie nutzen zu können, verwenden Sie bitte ausschließlich den oben genannten Link zum Abschluss Ihrer Stornoversicherung.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, er ist jetzt mit eingefügt. Passt das so vom Layout her?
