### ISSUE TITLE
Danke-Email - bitte checken

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#53]
Lieber Andreas,
wir hatten schon mal wegen der Text in den Email-Templates gesprochen. Ich habe hier im Bestätigungsemail grade noch den Stornohinweis adaptiert. Dabei ist mir aufgefallen, dass der Rechnungshinweis noch fehlerhaft ist. Der Text unten sollte nicht mehr sein:

_Falls Ihr Arbeitgeber die Kursgebühr überweist, geben Sie bitte die Rechnungsanschrift Ihres Arbeitgebers an.
{billing}_

Ich habe es nun so gemacht - und bin nicht sicher, ob das passt. Ich kanns grade nicht testen, da die Anmeldung nicht geht.

_**Rechnungsanschrift:**
{billing}_

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, das sieht super aus :) - Du kannst es jetzt auch wieder testen.

**Comment by ursulafeu** [comment]
Leider ist noch immer Fehlermeldung bei der Anmeldung. Trotz geleertem Cache.
![image](https://cloud.githubusercontent.com/assets/23695891/20976927/5ac905e2-bca4-11e6-9297-b4412e947490.png)

**Comment by Andreas-Schoenefeldt** [comment]
Danke, das du den gefunden hast - wenn man nicht seine Kontaktdaten teilen wollte, gab es eine Datenbank exception. Jetzt sollte es wirklich gehen.
