### ISSUE TITLE
Video - enable responsive includes

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#54]
Please check, weather this could be done via a shortcode https://www.drupal.org/project/shortcode - the actualvideo can then be made responsive by a container with a bottom padding percentage: https://coolestguidesontheplanet.com/videodrome/youtube/

**Comment by cydgit** [comment]
Andreas,

As we understand, you'd like to be able to enbed video into content and you suggest using this module: https://www.drupal.org/project/shortcode
The video should be displayed correctly for all devices (desktop, desktopnowide, tablet, mobile).
Is that correct?
It would be nice to have the requests in a bit clearer form so that we estimate exactly what is needed.

**Comment by Andreas-Schoenefeldt** [comment]
Hello, yes the video should be included in a responsive way, this can be achieved pretty simple by using an outer wrapper with a padding-bottom in % according to the aspect ratio to the video (as described in https://coolestguidesontheplanet.com/videodrome/youtube/)

This wrapper should not be done by the content editor, but included programmatically, that is why I suggested to look into the shortcode plugin, so the video could be included simply with something like: 

```
[video src="https://youtube.com/some-video" width="video-width" height="video-height"]
```

width and height can then be used to calculate the aspect ratio and the resulting padding-bottom of the wrapper div.

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , can we create a new custom module for this task?

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt 
Regarding the implementation - how else would you implement it?
We'd implement a small custom module where the text would be processed by a special function. The function will look for the code like [video src="https://youtube.com/some-video" width="video-width" height="video-height"] and display the video like it's specified in https://coolestguidesontheplanet.com/videodrome/youtube/

Content editors will see it like ![this](https://cloud.githubusercontent.com/assets/1660260/22536312/6b82d280-e933-11e6-91ce-28458c1a4fef.png)

We think it's rather simple, plus we can add the help text like on the screenshot.

**Comment by Andreas-Schoenefeldt** [comment]
Excellent, this sounds really great - please do so.

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , we committed the change.
To check it, you should:
1. Enable 'VT Video Shortcode' module.
2. After enabling it open 'admin/config/content/formats/manage/full_html' and enable 'Video shortcode'.
3. Then you can open admin/config/regional/translate and add the translation for these strings: 'Video shortcode', 'Provides video shortcode to text formats.'

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

you can now include videos in any text field using a shortcode:

```
[video src="https://www.youtube-nocookie.com/embed/RppToZPR9NA?rel=0&showinfo=0" width="560" height="315"]
```

It will generate a dynamic video include based on the values.

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Can you please check, why the video is not visible here: http://viszerale-therapie.at/pl/node/17
Thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Urusla, it is working now :) after an adjustment of cydgit. 

Please note, that the ```“``` character will lead to an error - it needs to be the ```"```. You have used ```width=“560“ height=“315“``` but it should be ```width="560" height="315"```

**Comment by ursulafeu** [comment]
great, thank you!
