### ISSUE TITLE
Ausrufezeichen Kursvoraussetzungen - Anmeldeformular 

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#55]
ist noch immer das Alte
![image](https://cloud.githubusercontent.com/assets/23695891/20933161/763e6862-bbd7-11e6-96d0-407c770d6fdd.png)

**Comment by Andreas-Schoenefeldt** [comment]
Done :)

**Comment by ursulafeu** [comment]
Danke Andreas, kannst Du es bitte noch viel näher zum Text rücken, anstatt linksbündig ausgerichtet.
danke!
![image](https://cloud.githubusercontent.com/assets/23695891/20976763/d9d0c376-bca3-11e6-8846-ca0a49a27d5b.png)

**Comment by Andreas-Schoenefeldt** [comment]
Jep, ist jetzt live.
