### ISSUE TITLE
Text Dankeseite - Korrektur

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#56]
Da fehlt das Wort "Tage" ... siehe Screenshot. danke

![image](https://cloud.githubusercontent.com/assets/23695891/20933974/f484eb36-bbd9-11e6-9f47-03fab74528a4.png)

**Comment by Andreas-Schoenefeldt** [comment]
Der Tag wird jetzt angezeigt, ich habe auch noch den Termin mit ausgegeben, zur sicherheit :)
