### ISSUE TITLE
Anmeldeformular - Zusatzhinweis Storno bei Schwangerschaft

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#57]
Platzierung: ganz unten zwischen dem Punkt „Schwangerschaft" und „Fahrgemeinschaften“

Aussehen: 
- klickbares Kästchen, wie z.B. „Arbeitgeber“
- Schrift kleiner als „Arbeitgeber“, soll nicht so auffällig sein

TEXT LAUTET:

**Stornoversicherung für eintretende Schwangerschaft**

Um anfallende Kosten für eine Stornierung des Kurses wegen Schwangerschaft zu vermeiden, raten wir zum Abschluss einer Stornoversicherung! 
Den Link zur Versicherung erhalten Sie nach Absenden dieses Formulares, sowie in Ihrem Bestätigungsemail. 
Nur bei Verwendung dieses Linkes und nur für Kursteilnehmerinnen der Schule für Viszerale Therapie gilt die Ausnahmeregelung bei Eintritt einer Schwangerschaft.
Die Zusatzklausel hierfür lautet:  "Eintritt einer Schwangerschaft der versicherten Person, wenn die Schwangerschaft erst nach Versicherungsabschluss festgestellt wurde“. Anbieter: Europäische Reiseversicherung (ERV)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, passt das so vom layout her oder ist es jetzt zu klein?

**Comment by ursulafeu** [comment]
Danke, aber es passt noch nicht. Sorry für die unpräzisen Angaben ... ich habs nochmal gelayoutet. Es schaut eigenartig aus, wenn es die gleiche Wertigkeit hat wie die anderen Balken. Die Schriftgröße allein löst das Problem nicht. Sorry für die doppelte Arbeit!

Farbe Rechteck innen: #EEEEEE
Farbe Rechteck Rand: #DDDDDD
Schriftfarbe: #555555
Rechteck Größe: 535px, Höhe: 30px

![image](https://cloud.githubusercontent.com/assets/23695891/20976176/feb78a00-bca1-11e6-8084-3c151fd5608a.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Urusla, Is it alright now?

**Comment by ursulafeu** [comment]
In your screenshot it looks fine, but at my end it looks like this: 
![image](https://cloud.githubusercontent.com/assets/23695891/23297996/16cb3d18-fa7c-11e6-8a1f-a4b39629eb30.png)

using Chrome, Mac

**Comment by Andreas-Schoenefeldt** [comment]
The font is to small?

**Comment by ursulafeu** [comment]
The font in the grey area is too small, please use the same size as used in the blue area above (Kursgebühr wird durch meinen Arbeitgeber bezahlt). danke!

**Comment by Andreas-Schoenefeldt** [comment]
Done :)
