### ISSUE TITLE
mobile view - registration flow

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#58]
**The registration layout is not ideal** 
![image](https://cloud.githubusercontent.com/assets/23695891/21043894/7d2ddb2a-bdf9-11e6-9e4f-203451e07537.png)

Please check, that on the registration confirmation, the layout is in a way, that no text overlap is happening. Before you do a registration, please make sure, that the test backend is connected, not the live one ;)

- Configuration > Development > VT Registration  (http://localhost:8000/admin/vt_registration/settings)

it should show backend-test.czeija.com as host.

**Comment by Andreas-Schoenefeldt** [comment]
Du hast die Schwangerschaft nicht akzeptiert, mich windert, das du das überhaupt abschicken konntest...

**Comment by Andreas-Schoenefeldt** [comment]
I Ursula, I think this is fixed now - it looks good to me.

**Comment by ursulafeu** [comment]
good now, thank you!
