### ISSUE TITLE
Alle VT Blocks übersetzbar machen

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#59]
Um die Übersetzungen im Frontend zu ermöglichen.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursual, this is possible now?

**Comment by ursulafeu** [comment]
yep, it works!! :) 👍 
The drop down fields in quick registration for example and registration in generell doesn't work.

**Comment by Andreas-Schoenefeldt** [comment]
I think we handle the rest of the registration in #63
