### ISSUE TITLE
Finish the Course Page

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [Andreas-Schoenefeldt/vt.at-drupal#6]

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, ich habe jetzt auf der Kursseite z.b ( http://preview.czeija.com/Kurse/abdomenpruefung ) das Schnellanmeldungs Widget eingebunden. Damit es funktioniert muss an jedem Kurs in Drupal noch die neue Backend Kurs ID eingetragen werden. 

Die Id kanst du im Backend unter http://backend.czeija.com/show/CourseType/ finden, wenn du dort die Kurse bearbeitest:

<img width="773" alt="screen shot 2016-11-28 at 12 28 30" src="https://cloud.githubusercontent.com/assets/1157580/20666781/389cdec0-b566-11e6-86e4-392d89752681.png">

Würdest du mich dort unterstützen und das für die anderen Kurse nachtragen?

1000 Dank
Andreas

**Comment by ursulafeu** [comment]
ist erledigt. In der Schnellanmeldung rechts steht allerdings immer "Aufbaukurs Thorax"

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, da hat noch ein Cache Tag gefehlt - es solte jetzt funktionieren?

**Comment by ursulafeu** [comment]
passt alles - wunderbar!
