### ISSUE TITLE
Übersetzungen - Verlinkung im Text nicht möglich

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#61]
**Wie verlinkt man im Text auf eine Englische Seite? Die wird nicht angezeigt in dem Link-Fenster ...**
wird z.b. hier benötigt bei den Voraussetzungen:
http://viszerale-therapie.at/en/Courses/master-class

**Comment by Andreas-Schoenefeldt** [comment]
ok, for now we will do it manuall...

**Comment by ursulafeu** [comment]
geht das auch mit dem systemlink .. /node/xyz ... ?

**Comment by ursulafeu** [comment]
hmmm ... da muss man wohl die language davor packen?? 
also /en/node/.... ???!

**Comment by Andreas-Schoenefeldt** [comment]
Ja genau, wenn du im Text verlinkst kannst du den System link mit dem language code davor im moment verwenden. Wenn wir dann die neue domain haben, wird das allerdings wegfallen.

Liebe Grüße
Andreas
