### ISSUE TITLE
CSS Main Menu Error

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#62]
on second level menu pages the top level is vanishing

![image](https://cloud.githubusercontent.com/assets/23695891/21381685/16c7cbee-c75d-11e6-8909-227fbd93b8d8.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hi guys, I think here is some kind of active link css in place. It might a side effect of the coloring of the right menu eg.: http://viszerale-therapie.at/ausbildung/agb

(the right menu should stay as it is, this fix should only affect the main navigation)

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , should we rename it to "Main menu error" maybe :-)?

**Comment by Andreas-Schoenefeldt** [comment]
jup, done :)

**Comment by cydgit** [comment]
@Andreas-Schoenefeldt , some clarifications are needed (also this is a follow-up of the discussion in https://github.com/Andreas-Schoenefeldt/vt.at-drupal/issues/49).

To clarify. Is it correct that:
1. The second menu level is blue, the third is grey.
2. The font should be bold on mouse-over; no background-color.
3. On menu hover, if the menu item is active, should this be reflected somehow?
4. Should any active menu item be displayed (for all levels)?

For example:
We're here: http://viszerale-therapie.at/ueber-uns/elfi-schlager
1. How should "Team" menu item be displayed, and how should it change on hover?
2. How should "Elfi Schlager" (li.active a) be displayed and how should the styles be updated on hover (li.active a:hover) ?

**Comment by cydgit** [comment]
Hi @ursulafeu ,

By the way, nice to meet you :-) It's Dmitry from Code Your Dream (I'm the main point of contact of our team).

Thank you for your reply.

To make it fully clear we recorded a video, can't attach it here, so here's the link: https://www.dropbox.com/s/1qp72lb1qv7olih/menu.mp4?dl=0
1. Should it all work as expected for the top menu (2nd and 3rd levels)?
2. Our changes will affect the left menu. Should it work as on the video?
3. Our changes don't affect the mobile version. Should we change something for mobile?
4. The screen you attached looks different in top menu. Should something be changed there? If yes, what exactly?

Thanks!

Kind Regards,
Dmitry

**Comment by ursulafeu** [comment]
Hi Dmitry, thank you, nice to meet you as well! :-)
Thank you also for the video - it looks very good! Please find my answers below.
Thank you, Ursula 

1. levels 2 and 3 - perfect now
2. left menu, changes are fine as shown in the video
3. mobile menu. Changes are needed - active items dark blue (#20376D) and bold please
4. top menu, yes it was intended differently. Please change the following:
a) font-color: #20376D 
b) active and hover: font-weight: bold --> is this possible without the whole menu "jumping"
If this is difficult or it takes time to change, so that it doesn't "jump", I would suggest another solution. Please let me know.

**Comment by cydgit** [comment]
@ursulafeu ,

Regarding this one:
> top menu, yes it was intended differently. Please change the following:
> b) active and hover: font-weight: bold --> is this possible without the whole menu "jumping"
> If this is difficult or it takes time to change, so that it doesn't "jump", I would suggest another solution. 

This might take some time to change indeed. There's a quicker solution - use text-shadow instead of font-weight: bold. Would that work for you?

Kind Regards,
Dmitry

**Comment by ursulafeu** [comment]
Yes, great idea - please go ahead with the suggested solution with text-shadow instead of bold.
Thank you! Kind regards, Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

is it good the way it is done and live now?

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Hi Andreas, most of the changes are missing. There has been a video on dropbox where the changes had been shown - it is no longer live unfortunately. Please can you check back with Dmitry? Thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I adjusted this with #82 now - is it ok like this now?

**Comment by ursulafeu** [comment]
Thank you! Function and drop down, everything looks good now! 
BUT one BUT ;) ... can you please use the same font as used in the left menu? I don't know why the main menu uses another font type (or is it only another size?). Thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Ok, I changed now the main menu font size and family to the one of the side menu.

**Comment by ursulafeu** [comment]
danke!
