### ISSUE TITLE
Language Version Course Boxes

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#63]
There is some kind of caching issue, which I was not able to resolve jet. It is about the boxes, which pull their data from the backend:

![fundierte ganzheitliche medizinische fortbildungen fur physiotherapeuten und arzte drupal](https://cloud.githubusercontent.com/assets/1157580/22289426/c4ee0abc-e2fb-11e6-9842-cca91e76d056.png)

The issue is, that the block is somehow cahced in the first language it gets hit, so if it is cached in german, no second language version is created for example for english, polish or russian.

I created [this](http://stackoverflow.com/questions/41232436/is-it-possible-to-have-multiple-cache-entries-depending-on-the-language-in-drupa) and [this](http://stackoverflow.com/questions/41232163/language-dependent-module-content-in-template-drupal-8?noredirect=1&lq=1) issue on stackoverflow, but it seems not to be a common problem or is not interesting enough.

I could imagine the following fixes, it can not be done in a nice and clean way:

1. try to add switches based on the language variable directly in the code (which blows it up and makes it ugly) - ```if lang == 'en' then ... else if lang == 'de' ...```
1. add custom cache tags, based on the language
1. try to find out how the drupal translation mechanism is implemented - the ```{% trans %}``` tag is just working well
1. last option: add a new block for every langauge and make the display language dependend (as done for the menus already)

**Comment by Andreas-Schoenefeldt** [comment]
Ja, das ist das selbe Caching "Feature", das wir auch mit der Kursübersicht - die Community schweigt sich aus. ich werd mal nen Issue einstellen und etwas rum experimentieren.

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
It works perfectly, thx a lot!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, 

the course selection and offer boxes work now well across languages. I'm happy we found the issue :). The missing translations like Dauer, Tage, etc are managed via the http://viszerale-therapie.at/admin/config/regional/translate administration interface.

Thx a lot!
Andreas

**Comment by ursulafeu** [comment]
Thank you! It works well!! :)
There is one spot missing though - please see screenshot. 
The words "Dauer" and "Tage" can't be translated.

![image](https://cloud.githubusercontent.com/assets/23695891/23026493/b2f113aa-f461-11e6-876c-fb4afa40d233.png)

**Comment by ursulafeu** [comment]
just found another spot that can't be translated:
--> "Tage"
![image](https://cloud.githubusercontent.com/assets/23695891/23026612/181e4e32-f462-11e6-8a4c-e2d8fc97395c.png)

**Comment by ursulafeu** [comment]
Andreas - your English is more profound than mine ... can we leave away the word "course" at "course length"? Is "length" only OK? That would solve the issue of line break here...

**Comment by ursulafeu** [comment]
one more: "Ihre Daten"
![image](https://cloud.githubusercontent.com/assets/23695891/23026783/a51f86fc-f462-11e6-9192-7173ee8f7c34.png)

**Comment by ursulafeu** [comment]
also here please: 
1) Title:"Frau / Herr" 
2) Academic Titel - 2 fields
![image](https://cloud.githubusercontent.com/assets/23695891/23027394/61ddca0a-f464-11e6-943b-c9a4438f465f.png)

**Comment by ursulafeu** [comment]
and this one: 
![image](https://cloud.githubusercontent.com/assets/23695891/23027461/8d665c32-f464-11e6-81a8-a856005836d0.png)

**Comment by Andreas-Schoenefeldt** [comment]
For the length, we can maybe choose "duration" - I think that is better. otherwise length is also fine?

**Comment by Andreas-Schoenefeldt** [comment]
The missing translations come with the next deployment later today.

**Comment by Andreas-Schoenefeldt** [comment]
The missing translations are now live :)

**Comment by ursulafeu** [comment]
Hi Andreas, not all of it is done - I deleted the comments that are done and left those, that are not fixed yet. Thank you!

**Comment by ursulafeu** [comment]
The word **Kurs** on homepage can't be translated too.
![image](https://cloud.githubusercontent.com/assets/23695891/23101350/bd731760-f691-11e6-92bb-4584a8df005d.png)

**Comment by ursulafeu** [comment]
Die Felder mit **TITEL** können auch noch nicht übersetzt werden.

**Comment by Andreas-Schoenefeldt** [comment]
The Warteliste text is already translatable if you search for "Warteliste" or "Um auf die Warteliste gesetzt zu werden, melden Sie sich bitte zum Kurs an. Wir informieren Sie umgehend wenn ein Platz frei wird oder ein zusätzlicher Termin zustande kommt."

- I found Kurs
- I found "Ihre Daten"
- I found the international and regular title fields

It will be live with the next deployment in a few.

**Comment by Andreas-Schoenefeldt** [comment]
Live now :)
