### ISSUE TITLE
Anmeldeformular - Textkorrektur Rücktrittskonditionen 

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#68]
bitte Absatz 1 und 2 ändern wie folgt, danke!

**Umbuchungen/Stornierug:** 
Im Falle einer Umbuchung/Stornierung (z.B. Kursdatum/Ort/Kurs) ist eine Bearbeitungsgebühr von € 30 zu bezahlen.

**Stornogebühr bis 6 Wochen vor Kursbeginn:** 
Rückerstattung des einbezahlten Kursbetrages abzüglich € 30 Bearbeitungsgebühr

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this is done, no?

**Comment by ursulafeu** [comment]
es haben sich einzelne Wörter geändert - vergleiche alte Version:
![image](https://cloud.githubusercontent.com/assets/23695891/22281794/14e1fb8c-e2d9-11e6-88b8-de030a55ed85.png)

**Comment by ursulafeu** [comment]
1) changes in the first paragraph: **Umbuchung/Stornierung**, instead of "Umbuchung"
2) changes second paragraph: "Rückerstattung", instead of "Rücküberweisung"

**Comment by Andreas-Schoenefeldt** [comment]
Will be live with the next deployment, I hope it does not affect already made translations... I think in the future, we should stick to the userinterface translations only and avoid changing the code keys. German can be overwritten as well.
