### ISSUE TITLE
Bestätigungsemail - Fahrgemeinschaft

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#69]
> Sie stimmen zu, dass Ihre Kontaktdaten den anderen Kursteilnehmern vor Kursbeginn übermittelt werden (zur Bildung von Fahrgemeinschaften): ${customer.shareContact}

Bitte für den oben genannten Satz folgende Änderung:

1) Bitte den ganzen Satz mit der Fahrgemeinschaft weglassen, wenn hier im Formular nicht bejaht wurde.

2) Wenn JA, dann bitte das : JA hinten weglassen. 
Sie stimmen zu, dass Ihre Kontaktdaten den anderen Kursteilnehmern vor Kursbeginn übermittelt werden (zur Bildung von Fahrgemeinschaften).

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this will make the email template a bit complicated - it is of course possible technically but will be a bigger efford for a relative small change. 

I understand, that it is nicer this way, but might not jsutify the cost. My suggestion would be to leave it as it is.

Best wishes
Andreas

**Comment by ursulafeu** [comment]
I spoke to Florinda about it - we leave it as it is, thank you.
