### ISSUE TITLE
Editor - Creating Links

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#7]
es ist nicht möglich externe Links zu setzen. Das System packt immer die "Basic-URL" der Seite davor.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

ich hab das eben mal mit http://google.de versucht und es hat funktioniert. Bei externen Links muss man immer das http:// oder das https:// mit ran schreiben. Klappt das bei dir?

**Comment by ursulafeu** [comment]
ja, sorry das klappt natürlich. Aber was nicht klappt ist, es in einem neuen Fenster öffnen zu lassen. 
Was muss ich da machen? Das war meine Herangehensweise: http://google.de _blank

**Comment by Andreas-Schoenefeldt** [comment]
ok, ich glaube das muss ich dir doch nen anderen Link button einbauen - ansonsten kann man auch auf Quellcode umstellen und dann target="_blank" direkt im a tag eintragen. 

Ich stell noch den normalen Link button mir online

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ich habe jetzt auch den normalen Link Button wieder sichtbar gemacht und noch ein Zusatzmodul isntalliert... (ist wohl kein standard feature), dort kann man auswählen, wo der Link sichtbar sein soll. Für eine Neue Seite wäre es dann die Checkbox "In neuem Fenster öffnen":

<img width="549" alt="screen shot 2016-11-23 at 13 03 03" src="https://cloud.githubusercontent.com/assets/1157580/20561176/78325598-b17d-11e6-8ff9-9bdbaf251434.png">

**Comment by ursulafeu** [comment]
danke - perfekt! :)
