### ISSUE TITLE
course registration form - language versions

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#70]
**English - please cut out the following paragraphs:**
-> "Umbuchung oder Stornierung"
-> "Die Kursgebühr wird durch meinen Arbeitgeber bezahlt"
-> "Stornoversicherung für eintretende Schwangerschaft"
-> "Ich stimme zu, dass meine Kontaktdaten den anderen Kursteilnehmern vor Kursbeginn übermittelt werden (zur Bildung von Fahrgemeinschaften)."

**Polish - please cut out the following paragraphs:**
-> "Umbuchung oder Stornierung"
-> "Die Kursgebühr wird durch meinen Arbeitgeber bezahlt"
-> "Stornoversicherung für eintretende Schwangerschaft"

**Russian - can stay the same as here - http://www.visceral-therapy.com/vt/anmeldung.php?lang=ru&kurs=263**
But please cut out the following paragraphs: 
--> second to last paragraph: 
В случае отсутствия свободных мест на ближайший курс, прошу записать меня в лист ожидания и информировать о дополнительных семинарах.
--> last paragraph: 
Я соглашаюсь с тем, что мои контактные данные будут предоставлены участникам моей учебной группы

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this is live now - is it ok like this (you might need to clear your cache)

**Comment by ursulafeu** [comment]
Hi Andreas, can you please add EN translation for the cancellation text - is still German
(see here for example: http://viszerale-therapie.at/en/register/7?course-id=275)

In case of a cancellation of registration by no later than 6 weeks before the course start date, course fees already paid will be transferred back in full to the applicant’s bank account, after the deduction of a € 30.00 handling charge. Costs incurred by an international credit transfer are chargeable to the applicant.

In case of cancellation of registration by no later than 4 weeks before the course start date, the participant incurs a cancellation fee of 30% of the course fees.

In case of cancellation of registration by no later than 2 weeks before the course start date, the participant incurs a cancellation fee of 50% of the course fees.

In case of cancellation of registration within 2 weeks before the course start date or during the course, the participant incurs a cancellation fee of 100% of the course fees.

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, 
can we get this into the given form - all lines have a translation tag, but without the :

```html
<h3>{% trans %}Umbuchung/Stornierung{% endtrans %}:</h3>
<p>{% trans %}Im Fall einer Umbuchung (z.B. Kursdatum / Ort / Kurs) ist eine Bearbeitungsgebühr von € 30 zu bezahlen.{% endtrans %}</p>

<h3>{% trans %}Stornogebühr bis 6 Wochen vor Kursbeginn{% endtrans %}:</h3>
<p>{% trans %}Rückerstattung des einbezahlten Kursbetrages abzüglich € 30 Bearbeitungsgebühr{% endtrans %}</p>

<h3>{% trans %}Stornogebühr 6 - 4 Wochen vor Kursbeginn{% endtrans %}:</h3>
<p>{% trans %}30 % der Kursgebühr + € 30 Bearbeitungsgebühr{% endtrans %}</p>

<h3>{% trans %}Stornogebühr 4 - 2 Wochen vor Kursbeginn{% endtrans %}:</h3>
<p>{% trans %}50 % der Kursgebühr + € 30 Bearbeitungsgebühr{% endtrans %}</p>

<h3>{% trans %}Stornogebühr 2 Wochen vor Kursbeginn oder während des Kurses{% endtrans %}:</h3>
<p>{% trans %}100 % der Kursgebühren + € 30 Bearbeitungsgebühr{% endtrans %}</p>
```

**Comment by ursulafeu** [comment]
great, thank you!
