### ISSUE TITLE
Fotos - Vergrößerung mit Lightbox

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#8]

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursual, wo soll das passieren?

**Comment by ursulafeu** [comment]
bei den drei Kursfotos ganz unten. 
Optimal wäre, wenn man das optional auch im normalen Content machen kann. Aber Prio haben sicher die Kursfotos.

**Comment by Andreas-Schoenefeldt** [comment]
Should be done together with #34 now 😄
