### ISSUE TITLE
help needed - box translations

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#80]
Hi Andreas, I translated the right box with AGB download into Polish:  http://viszerale-therapie.at/ausbildung/agb
It is not visible - I think I did something wrong but I can't find the mistake. Can you please help with the issue?

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this is indeed a bit confusing... there are two levels - the block itself (Block Konfigurieren) http://viszerale-therapie.at/admin/structure/block/manage/agbdownload?destination=node/7 and the content of the Block, which is handled via the translations.

I enabled it now for all 4 languages - is it visible now?

**Comment by ursulafeu** [comment]
OK, I remember ... thank you - visible now!
