### ISSUE TITLE
Textlinks for Language versions

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#83]
Andreas, I can't remember the latest info sorry. 
Add a textlink to another internal page is not possible for the corresponding language version, for example here: http://viszerale-therapie.at/pl/node/25

What to do about that?

**Comment by ursulafeu** [comment]
This is the current solution I am using for internal text links: /en/about-us/our-team
Can you make this work with the new domains also? So that I don't have to change all the links again?

**Comment by Andreas-Schoenefeldt** [comment]
Ah - I'll create interims domains, so that we can do it in one go

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

there are now the language interim domains:

http://en.viszerale-therapie.at/
http://pl.viszerale-therapie.at/
http://ru.viszerale-therapie.at/

We will replace them by the real ones once we think the content is good to go.

Regarding the text links, the should be stable now, if you use internal ones (without "http://en.viszerale-therapie.at/")

Best wishes
Andreas

**Comment by ursulafeu** [comment]
Thank you Andreas. What does that mean for me? Do I have to change the textlinks now? 
Please let me know. Thank you and best wishes, Ursula

**Comment by Andreas-Schoenefeldt** [comment]
We still need to change it maually, if I'm right, but with #90 it should be much more easy now to find the correct link. Please use only relative urls, so that we don't need to change again, after weconnected the correct domain.
