### ISSUE TITLE
PL - Übersetzung wird nicht ausgegeben

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#88]
KURSANMELDUNG ist im Backend übersetzt, wird aber nicht ausgegeben:
http://viszerale-therapie.at/pl/node/17

**Comment by Andreas-Schoenefeldt** [comment]
Ich glaub der Cache war nicht gelöscht - ich kann den Fehler nicht mehr nachvollziehen. Wenn er noch da ist, kannst du bitte einen Screenshot anhängen?

**Comment by ursulafeu** [comment]
alles gut, fehler weg. danke
