### ISSUE TITLE
internal links

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#9]
interne Links werden z.B. so dargestellt: .../**node/30**
hier sind ein paar interne links zum Ansehen: http://preview.czeija.com/pruefungen
Kannst Du das bitte ändern, sodass auch bei internen Links die speaking URLs verwendet werden?

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

ich habe jetzt einmal die pfade eingestellt für Deutsch und Englisch. Damit die neue URL generiert wird, wäre es toll, wenn du bei jedem Kurs einmal das "Generate automatic URL alias" Häkchen setzen könntest und ihn nochmal abspeicherst:

<img width="701" alt="screen shot 2016-11-24 at 13 02 58" src="https://cloud.githubusercontent.com/assets/1157580/20597920/bbea56cc-b246-11e6-9d26-c61f2ff6596b.png">

Danke 😸

**Comment by ursulafeu** [comment]
ist erledigt
