### ISSUE TITLE
home PL - course title cut off

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#92]
http://pl.viszerale-therapie.at/

Hi Andreas, one course title is cut off. Do you have an idea what to do about that?

**Comment by Andreas-Schoenefeldt** [comment]
Can we do shorter titles in PL? Ok joke ;) I’ll have a look

**Comment by ursulafeu** [comment]
Well you never know, I just rechecked the course title, it is actually really correct, unbelievable. 
Anyway - thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Alright, so I made the box for pl (only) heigher: http://terapia-wisceralna.pl/ - I still think this single title could maybe be rewritten in polish - seems to be very complicated ;)
