### ISSUE TITLE
PL youtube videos not visible

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#93]
Can you please check why the video is not visible - I just replaced the link from the German Video. I don't know what went wrong.

http://pl.viszerale-therapie.at/kursy/kurs-rozszerzony-klatka-piersiowa

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, I think iFrame is not part of the allowed tags, which is ok (bacause the iframe in itself is not responsive) - please only use the shortcode to include videaos:

[video src="https://some-embed-video" width="video-width" height="video-height"]

**Comment by ursulafeu** [comment]
Sorry I need more assistance please, that doesn't work either?
http://pl.viszerale-therapie.at/kursy/nieplodnosc-ciaza-i-porod

**Comment by ursulafeu** [comment]
thank you, this is done.
