### ISSUE TITLE
URLs Sprachversionen ändern

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#94]
Lieber Andreas, da hatten wir zuletzt am Telefon nicht mehr über die Lösung gesprochen, soweit ich weiß?
Kannst Du mir bitte zeigen wo ich z.B. diese beiden URLs ändern kann?
http://pl.viszerale-therapie.at/seminarorte/lokalizacja-kursow-w-austrii
http://pl.viszerale-therapie.at/uber-uns/nasz-zespol

Und kann man das Backend für die Sprachversionen trotzdem Deutsch oder Englisch machen?

**Comment by Andreas-Schoenefeldt** [comment]
Das Backend ist nur dann in deutsch, wenn du auf die deutsche Seite gehst und dort die Übersetzungen bearbeitest. Die Seite direkt sieht man leider nur auf der entsprechenden Sprachseite.
