### ISSUE TITLE
Youtube video - responsive

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#95]
Hi Andreas,
kannst Du mir bitte nochmals den Quellcode schicken, wie man ein Video einbetten muss? Wenn ich die Höhe einfach entferne und bei width 100% eingebe, dann ist das Video abgeschnitten - siehe hier:
http://viszerale-therapie.at/Kurse/tinnitus-schwindel-kiefergelenksprobleme-zahnspange

Danke!!

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 

wir hatten ja diesen Shortcode gebaut. Du kannst einfach im Content z.b. folgendes angeben:

```
[video src="https://www.youtube.com/embed/9ly44aS-L-Y?list=PL5LeElULfSL2_4fKX6sWuBeMIY8tB_I6X" width="560" height="315"]
```
Den Rest machen wir automatisch - du überträgst praktisch nur die Werte aus dem Embedd Dialaog von YouTube

<img width="868" alt="screen shot 2017-05-03 at 18 19 23" src="https://cloud.githubusercontent.com/assets/1157580/25670492/2431ece0-302d-11e7-8073-314e3dcb0fac.png">

**Comment by ursulafeu** [comment]
danke, ja das klappt wunderbar.
