### ISSUE TITLE
Registration Error 

### ISSUE THREAD

**Issue by ursulafeu** [Andreas-Schoenefeldt/vt.at-drupal#99]
Hi Andreas,
ich hab grade auf Englisch eine Anmeldung gemacht.
**1) Ich brauche den Text auf der Bestätigungsseite - kannst Du mir den bitte schicken.**
2) Beim Absenden kommt ein Error:
![image](https://cloud.githubusercontent.com/assets/23695891/26302522/ce429cdc-3ee4-11e7-820d-ee2de12ebd5b.png)

Bitte dringend richten und checken, ob es bei den anderen Sprachen auch nicht geht. Danke!!
LG; Ursula

**Comment by ursulafeu** [comment]
Im Backend ist die Anmeldung auch nicht angekommen und auch keine Kursbestätigung per Email. 
Die Anmeldung war bei diesem Kurs: http://visceral-therapy.com/Courses/physiological-nutrition

**Comment by Andreas-Schoenefeldt** [comment]
Sehr Cool,  das Problem geistert die letzten Wochen schon rum, ohne das es wirklich eingrenzbar wäre.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 

ich kann es leider immer noch nicht nachvollziehen, bei mir klappt alles - welchen browser und welches Betriebssystem verwendest du?

Kannst du den Fehler eventuell noch etwas genauer nachstellen?

1000 Dank
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Ach so, auf der Fehlerseite, was stand oben in der adress-zeile?

**Comment by ursulafeu** [comment]
da steht: http://visceral-therapy.com/submit/7
und Browser ist Google Chrome, Version 58.0.3029.110 (64-bit)

**Comment by Andreas-Schoenefeldt** [comment]
Fixed with #103
